services:
  app:
    build: .
    container_name: fastapi_app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
